from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_avaiblable():
    response = client.get("/")
    assert response.status_code == 200
    assert response.json() == {"message": "Hello World!!!!!"}

def test_get_permission():
    response = client.post("/get_permission?package_name=org.woheller69.spritpreise&version_code=24")
    assert response.status_code == 200
    assert response.json() == {"permissions":["android.permission.ACCESS_COARSE_LOCATION"]}
    response = client.post("/get_permission?package_name=com.zhiliaoapp.musically&version_code=2022903010")
    assert response.status_code == 200
    assert set(response.json()["permissions"]) == set(['android.permission.SYSTEM_ALERT_WINDOW', 'android.permission.RECORD_AUDIO', 'android.permission.CAMERA', 'android.permission.WAKE_LOCK', 'android.permission.WRITE_EXTERNAL_STORAGE', 'android.permission.FOREGROUND_SERVICE', 'android.permission.INTERNET'])

def test_get_acitivities():
    response = client.post("/get_acitivities?package_name=org.woheller69.spritpreise&version_code=24")
    assert response.status_code == 200
    assert response.json() == {"activities":["org.woheller69.spritpreise.activities.AboutActivity","org.woheller69.spritpreise.firststart.TutorialActivity","org.woheller69.spritpreise.activities.ManageLocationsActivity","org.woheller69.spritpreise.activities.SettingsActivity","org.woheller69.spritpreise.activities.CityGasPricesActivity"]}
    response = client.post("/get_acitivities?package_name=org.wikipedia.alpha&version_code=50476")
    assert response.status_code == 200
    assert response.json() == {"activities":["org.wikipedia.settings.languages.WikipediaLanguagesActivity","org.wikipedia.places.PlacesActivity","org.wikipedia.theme.ThemeFittingRoomActivity","org.wikipedia.main.MainActivity","org.wikipedia.page.tabs.TabActivity","org.wikipedia.edit.EditSectionActivity","org.wikipedia.page.PageActivity","org.wikipedia.talk.TalkTopicsActivity","org.wikipedia.talk.TalkReplyActivity","org.wikipedia.language.LanguagesListActivity","org.wikipedia.diff.ArticleEditDetailsActivity","org.wikipedia.createaccount.CreateAccountActivity","org.wikipedia.settings.AboutActivity","org.wikipedia.language.LangLinksActivity","org.wikipedia.readinglist.ReadingListActivity","org.wikipedia.page.edithistory.EditHistoryListActivity","org.wikipedia.feed.configure.ConfigureActivity","org.wikipedia.settings.SettingsActivity","org.wikipedia.onboarding.InitialOnboardingActivity","org.wikipedia.settings.LicenseActivity","org.wikipedia.search.SearchActivity"]}
    response = client.post("/get_acitivities?package_name=com.amaze.filemanager&version_code=117")
    assert response.status_code == 200
    assert response.json() == {"activities":["com.amaze.filemanager.ui.activities.AboutActivity","com.amaze.filemanager.ui.activities.PreferencesActivity","com.amaze.filemanager.ui.activities.MainActivity","com.amaze.filemanager.ui.activities.texteditor.TextEditorActivity","com.mikepenz.aboutlibraries.ui.LibsActivity"]}
    response = client.post("/get_acitivities?package_name=com.zhiliaoapp.musically&version_code=2022903010")
    assert response.status_code == 200
    assert response.json() == {"activities":["com.ss.android.ugc.aweme.livewallpaper.ui.LocalLiveWallPaperActivity","com.ss.android.ugc.aweme.ecommerce.showcase.showcase.ShowcaseActivity","com.ss.android.ugc.aweme.share.qrcode.UserQRCodeActivity","com.ss.android.ugc.aweme.crossplatform.activity.CrossPlatformActivity","com.ss.android.ugc.aweme.compliance.business.filtervideo.ui.activity.FilterVideoKeywordsActivity","com.ss.android.ugc.aweme.ecommerce.base.pdp.ui.PdpActivity","com.ss.android.ugc.aweme.detail.ui.DetailActivity","com.ss.android.ugc.aweme.qrcode.view.ScanQRCodeActivityV2","com.bytedance.ies.ugc.aweme.commercialize.compliance.inference.AdInferenceActivity","com.ss.android.ugc.aweme.live.LivePlayActivity","com.ss.android.ugc.aweme.setting.ui.PushSettingNotificationChoiceActivity","com.ss.android.ugc.aweme.music.ui.MusicDetailActivity","com.bytedance.ies.ugc.aweme.commercialize.compliance.personalization.AdPersonalizationActivity","com.ss.android.ugc.aweme.host.TikTokHostActivity","com.bytedance.hybrid.spark.page.SparkActivity","com.ss.android.ugc.aweme.notification.MusNotificationDetailActivity","com.ss.android.ugc.aweme.im.sdk.chat.ui.powerpage.SelectChatMsgHostActivity","com.ss.android.ugc.aweme.account.login.auth.I18nSignUpActivity","com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity","com.ss.android.ugc.aweme.search.pages.core.ui.activity.SearchResultActivity","com.ss.android.ugc.aweme.relation.ffp.ui.FindFriendsPageActivity","com.ss.android.ugc.aweme.im.sdk.relations.ui.activity.RelationSelectActivity","com.ss.android.ugc.aweme.setting.I18nSettingManageMyAccountActivity","com.ss.android.ugc.aweme.im.sdk.chatdetail.ui.activity.FriendChatDetailActivity","com.ss.android.ugc.aweme.splash.SplashActivity","com.bytedance.lobby.instagram.InstagramAuthActivity","com.ss.android.ugc.aweme.setting.ui.SettingContainerActivity","com.ss.android.ugc.aweme.watch.history.core.WatchHistoryActivity","com.ss.android.ugc.aweme.account.login.v2.ui.SignUpOrLoginActivity","com.ss.android.ugc.aweme.ecommerce.base.osp.page.OrderSubmitActivity","com.ss.android.ugc.aweme.wiki.AddWikiActivity","com.ss.android.ugc.trill.setting.ContentPreferenceActivity","com.ss.android.ugc.aweme.shortvideo.mvtemplate.choosemedia.MvChoosePhotoActivity","com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity","com.ss.android.ugc.aweme.mix.videodetail.MixVideoDetailActivity","com.ss.android.ugc.aweme.creatortools.CreatorToolsActivity","com.ss.android.ugc.aweme.journey.NewUserJourneyActivity","com.ss.android.ugc.aweme.profile.ui.ProfileEditActivity","com.ss.android.ugc.aweme.following.ui.FollowRelationTabActivity","com.ss.android.ugc.aweme.shortvideo.edit.VEVideoPublishEditActivity","com.bytedance.ies.ugc.aweme.commercialize.compliance.advertiser.AdvertiserSettingsActivity"]}
    
def test_debloat_activity():
    response = client.post("/debloat_activity?package_name=org.woheller69.spritpreise&version_code=24&activity_names=org.woheller69.spritpreise.activities.ManageLocationsActivity,org.woheller69.spritpreise.activities.AboutActivity")
    assert response.status_code == 200
    assert set(response.json()["to_remove_methods"]) == set(["<org.woheller69.spritpreise.activities.ManageLocationsActivity: void onDestroy()>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: void <init>()>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: void addCityToList(org.woheller69.spritpreise.database.City)>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: org.woheller69.spritpreise.database.CityToWatch convertCityToWatched(org.woheller69.spritpreise.database.City)>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: void onCreate(android.os.Bundle)>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: void onResume()>","<org.woheller69.spritpreise.activities.ManageLocationsActivity: int getNavigationDrawerID()>","<org.woheller69.spritpreise.activities.AboutActivity: void onCreate(android.os.Bundle)>","<org.woheller69.spritpreise.activities.AboutActivity: void <init>()>","<org.woheller69.spritpreise.activities.AboutActivity: int getNavigationDrawerID()>"])
    assert set(response.json()["to_remove_permissions"]) == set()
    response = client.post("/debloat_activity?package_name=com.zhiliaoapp.musically&version_code=2022903010&activity_names=com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity,com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity")
    assert response.status_code == 200
    assert set(response.json()["to_remove_methods"]) == set(["<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onResume()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onPause()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onSaveInstanceState(android.os.Bundle)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: boolean dJ_()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZJ(X.GcK)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZ(com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void finish()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZ(boolean)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onRestoreInstanceState(android.os.Bundle)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZ(X.GcL)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZIZ(X.GcL)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onStop()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onDestroy()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LJII()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZIZ(boolean)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: boolean LIZ(android.content.Intent)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void <init>()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void LIZIZ(X.GcK)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onCreate(android.os.Bundle)>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: android.content.Intent getIntent()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: X.X6W getInflater()>","<com.ss.android.ugc.aweme.shortvideo.ui.VideoRecordNewActivity: void onStart()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onCreate(android.os.Bundle)>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: java.lang.String getBtmPageCode()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onStart()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onResume()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void <init>()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onDestroy()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: android.content.Intent getIntent()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onPause()>","<com.ss.android.ugc.aweme.ecommerce.showcase.store.StoreActivity: void onStop()>"])
    assert set(response.json()["to_remove_permissions"]) == set()
    
def test_debloat_permission():
    response = client.post("/debloat_permission?package_name=org.woheller69.spritpreise&version_code=24&permissions=android.permission.ACCESS_FINE_LOCATION,android.permission.ACCESS_COARSE_LOCATION,android.permission.ACCESS_BACKGROUND_LOCATION")
    assert response.status_code == 200
    assert set(response.json()["to_remove_methods"]) == set(["<org.woheller69.spritpreise.activities.SettingsActivity: void onRequestPermissionsResult(int,java.lang.String[],int[])>"])
    assert set(response.json()["to_remove_permissions"]) == set(["android.permission.ACCESS_FINE_LOCATION","android.permission.ACCESS_COARSE_LOCATION","android.permission.ACCESS_BACKGROUND_LOCATION"])